version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting deployment to ECS..."
      - IMAGE_URI=$(cat imageDefinition.json | jq -r '.ImageURI')
      - TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition $TASK_DEFINITION_FAMILY --query taskDefinition)
      - echo $TASK_DEFINITION > taskdef.json
      - NEW_TASK_DEFINITION=$(echo $TASK_DEFINITION | jq --arg IMAGE "$IMAGE_URI" '.containerDefinitions[0].image = $IMAGE')

  build:
    commands:
      - echo "Registering new task definition..."
      - NEW_TASK_DEF=$(aws ecs register-task-definition --cli-input-json "$NEW_TASK_DEFINITION" --query 'taskDefinition.taskDefinitionArn' --output text)
      - echo "New task definition: $NEW_TASK_DEF"

  post_build:
    commands:
      - echo "Updating ECS service..."
      - aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --task-definition $NEW_TASK_DEF --force-new-deployment
      - echo "Waiting for service to stabilize..."
      - aws ecs wait services-stable --cluster $ECS_CLUSTER_NAME --services $ECS_SERVICE_NAME
      - echo "Deployment completed on $(date)"

artifacts:
  files:
    - imageDefinition.json
    - taskdef.json